spring:
  jpa:
    show-sql: false
  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
      show-components: never

logging:
  level:
    root: WARN
    com.taskbot: INFO
  file:
    name: /var/log/taskbot/app.log

server:
  tomcat:
    threads:
      max: 100
      min-spare: 10
    max-connections: 200